eSchoolSemi/Areas/AdministratorModul/Controllers/UcenikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchoolSemi.Data;
using Microsoft.AspNetCore.Mvc;
using eSchool.Data.Models;
using eSchoolSemi.Web.Areas.AdministratorModul.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using eSchoolSemi.Web.Helper;
using eSchoolSemi.Data.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Diagnostics;

namespace eSchoolSemi.Web.Areas.AdministratorModul.Controllers
{
    

    [Area("AdministratorModul")]
    [Autorizacija(false, false, false, true)]
    public class UcenikController : Controller
    {
        private MojContext _context;


        public UcenikController(MojContext context) => _context = context;

        public string sortFilter = "empty";
       

        public IActionResult Index()
        {

           



           
            



            return View();
        }

        

        public async Task<IActionResult> _tabela(string sortOrder,string currentFilter,string searchString,int? page) {

            
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : ""; 

            IQueryable<Ucenik> listaUcenika = from x in _context._Ucenik
                                              select x;
            

            if (!String.IsNullOrEmpty(searchString))
            {
                           
               
                listaUcenika = listaUcenika.Where(x => (x.Ime + x.Prezime).Contains(searchString) ||(x.Prezime +" "+ x.Ime).Contains(searchString));
            }

           

                switch (sortOrder)
                {
                    case "name_desc":
                        listaUcenika = listaUcenika.OrderByDescending(x => x.Prezime);
                        break;
                    default:
                        listaUcenika = listaUcenika.OrderBy(x => x.Prezime);
                        break;
                }

            
            




           




            int pageSize = 10;
            return PartialView(await PaginatedList<Ucenik>.CreateAsync(listaUcenika.AsNoTracking(), page ?? 1, pageSize));

        }

        public IActionResult DodajUcenikaOdlj() {


            OdjeljenjeUcenikVm dodavanjeUcenik = new OdjeljenjeUcenikVm();
                      

            return PartialView(DefaultVM(dodavanjeUcenik));
        }

        public JsonResult vratiOdjlejenje(int GodinaID, int RazredID) {


             var odabranaOdljenja = _context._Odjeljenje.Where(x => x.GodinaStudijaId == GodinaID && x.RazredID == RazredID && _context._UpisUOdjeljenje.Where(s=>s.OdjeljenjeId==x.OdjeljenjeId).Count()<x.Kapacitet).
                                            Select(x => new SelectListItem {
                                                Value=x.OdjeljenjeId.ToString(),
                                                Text=x.Oznaka

                                            }).ToList();


            return Json(odabranaOdljenja);
        }

        public IActionResult snimiUpis(int UcenikId,int OdjeljenjeId) {


            if (UcenikId != 0 && OdjeljenjeId != 0) { 

            UpisUOdjeljenje noviUpis = new UpisUOdjeljenje {

                UcenikId = UcenikId,
                OdjeljenjeId = OdjeljenjeId,
                BrojUDnevniku = 0
            };

            _context._UpisUOdjeljenje.Add(noviUpis);
            _context.SaveChanges();

            IEnumerable<UpisUOdjeljenje> listaUcenika = _context._UpisUOdjeljenje.Where(x => x.OdjeljenjeId == OdjeljenjeId).Include(x => x.Ucenik).ToList();

            listaUcenika = listaUcenika.OrderBy(x => x.Ucenik.Prezime);

            int brojac = 1;
            foreach (var ucenik in listaUcenika) {

                ucenik.BrojUDnevniku = brojac;
                brojac++;

            }

           
            _context.SaveChanges();

            }

            return RedirectToAction(nameof(Index));

        }




        public JsonResult nazivUcenika(string Prefix) {

            List<SelectListItem> ucenik = _context._Ucenik.Where(x => (x.Ime + " " + x.Prezime).StartsWith(Prefix)||( x.Prezime + " " + x.Ime).StartsWith(Prefix)).Select(x => new SelectListItem
            {

                Value = x.KorisnikId.ToString(),
                Text = x.Prezime + " " + x.Ime
            }).ToList();
            

           

            return Json(ucenik);
        }


        public JsonResult nazivRoditelja(string Prefix)
        {

            List<SelectListItem> ucenik = _context._Roditelj.Where(x => (x.Ime + " " + x.Prezime).StartsWith(Prefix) || (x.Prezime + " " + x.Ime).StartsWith(Prefix)).Select(x => new SelectListItem
            {

                Value = x.KorisnikId.ToString(),
                Text = x.Prezime + " " + x.Ime
            }).ToList();




            return Json(ucenik);
        }

        public IActionResult DodajUcenika()
        {
            UcenikDodajVM vm = new UcenikDodajVM();
            vm.DatumRodjenja= new DateTime(DateTime.Now.Year - 14, DateTime.Now.Month, DateTime.Now.Day);



            return PartialView(GetDefaultVM(vm));
        }

        public IActionResult DodajFile()
        {
            Ucenik ucenik = _context._Ucenik.FirstOrDefault();

            return View(ucenik);
        }

        
        [HttpPost]
        public async Task<IActionResult> SnimiUcenika(UcenikDodajVM vm)
        {




            if (!ModelState.IsValid)
            {
               
                return View("DodajUcenika", GetDefaultVM(vm));
            }


            Roditelj roditelj = _context._Roditelj.FirstOrDefault(x => x.Prezime + " " + x.Ime == vm.Roditelj);

            string passwordGen = Guid.NewGuid().ToString("N").Substring(0, 10);

            KorisnickiNalog korisnicki = new KorisnickiNalog
            {
                Username = vm.Username,
                Password = passwordGen,
                Zapamti = false
            };

            _context.korisnickiNalogs.Add(korisnicki);
            _context.SaveChanges();

            Ucenik noviUcenik = new Ucenik
            {

                Ime = vm.Ime,
                Prezime = vm.Prezime,
                Telefon = vm.Telefon,
                Email = vm.Email,
                GradId = vm.GradID,
                KorisnickoIme = vm.Username,
                Lozinka = passwordGen,
                KorisnickiNalogID = _context.korisnickiNalogs.FirstOrDefault(x => x.Username == vm.Username && x.Password == passwordGen).KorisnickiNalogID,
                DatumRodenja = vm.DatumRodjenja,
                Vladanje = "Primjerno",
                RoditeljId=roditelj?.KorisnikId
                

            };

           

            if (vm.KorinickaSlika != null)
            {
                using (var memoryStream = new MemoryStream())
                {

                    await vm.KorinickaSlika.CopyToAsync(memoryStream);
                    noviUcenik.KorisnickaSlika = memoryStream.ToArray();
                }
            }





            _context._Ucenik.Add(noviUcenik);
            _context.SaveChanges();

          
            return RedirectToAction("Index");

        }




        #region glupeFunkcije

        public UcenikDodajVM GetDefaultVM(UcenikDodajVM vm)
        {

         

            if (vm.Gradovi==null)
            {
                vm.Gradovi = _context._Grad.Select(x => new SelectListItem
                {
                    Value = x.GradId.ToString(),
                    Text=x.Naziv
                }).ToList();
            }

            if (vm.Roditleji == null)
            {
                vm.Roditleji = _context._Roditelj.Select(x => new SelectListItem
                {
                    Value = x.KorisnikId.ToString(),
                    Text = x.Ime + " " + x.Prezime
                }).ToList();
            }

            

            return vm;
        }

        public OdjeljenjeUcenikVm DefaultVM(OdjeljenjeUcenikVm vm)
        {



            vm.Ucenici = _context._Ucenik.Where(x => !_context._UpisUOdjeljenje.Any(s => s.UcenikId == x.KorisnikId)).Select(x => new SelectListItem
            {

                Value = x.KorisnikId.ToString(),
                Text = x.Prezime + " " + x.Ime

            }).ToList();

            var godinaStudija = _context._GodinaStudija.FirstOrDefault(x => x.TrenutnaGodina == true);
            vm.GodinaStudijaId = godinaStudija.GodinaStudijaId;
            vm.GodineStudija = godinaStudija.Godina;

            vm.Razredi = _context.Razred.Select(x => new SelectListItem
            {

                Value = x.RazredId.ToString(),
                Text = x.OpisRazreda

            }).ToList();




            return vm;
        }

        public UcenikUrediVM Popuni(UcenikUrediVM vm)
        {



            if (vm.Gradovi == null)
            {
                vm.Gradovi = _context._Grad.Select(x => new SelectListItem
                {
                    Value = x.GradId.ToString(),
                    Text = x.Naziv
                }).ToList();
            }





            return vm;
        }
        #endregion

        public IActionResult Obrisi(int UcenikID)
        {


            Ucenik izbrisi = _context._Ucenik.FirstOrDefault(x => x.KorisnikId == UcenikID);
            KorisnickiNalog korisnicki = _context.korisnickiNalogs.FirstOrDefault(x => x.KorisnickiNalogID == izbrisi.KorisnickiNalogID);
            var Odjeljenje = _context._Odjeljenje.FirstOrDefault(x => x.UcenikID == UcenikID);
            var upisanaOdjeljenja = _context._UpisUOdjeljenje.Where(x => x.UcenikId == UcenikID).ToList();

            foreach (var upis in upisanaOdjeljenja)
            {
                IEnumerable<UpisUOdjeljenje> obj = _context._UpisUOdjeljenje.Where(x => x.OdjeljenjeId == upis.OdjeljenjeId).Include(s=>s.Ucenik).ToArray();

                _context._UpisUOdjeljenje.Remove(upis);
                              

eSchoolSemi/Areas/RoditeljModul/Controllers/UcenikController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchool.Data.Models;
using eSchoolSemi.Data;
using eSchoolSemi.Data.Models;
using eSchoolSemi.Web.Areas.RoditeljModul.ViewModels;
using eSchoolSemi.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eSchoolSemi.Web.Areas.RoditeljModul.Controllers
{
    [Area("RoditeljModul")]
    [Autorizacija(false, false, true, false)]
    public class UcenikController : Controller
    {
        private MojContext db;
        public UcenikController(MojContext _db) { db = _db; }
        public IActionResult Index()
        {
            KorisnickiNalog k = HttpContext.GetLogiraniKorisnik();
            Korisnik roditelj = db._Korisnik.Where(x => x.KorisnickiNalogID == k.KorisnickiNalogID)
                .Include(r => r.KorisnickiNalog).FirstOrDefault();

            UcenikIndexVM vm = new UcenikIndexVM() {
                 Rows=   db._Ucenik.Where(x => x.RoditeljId == roditelj.KorisnikId).Select(u => new UcenikIndexVM.Row()
                {
                    ImePrezime = u.Ime+" "+u.Prezime,
                    UcenikID = u.KorisnikId,
                    Vladanje=u.Vladanje,
                    DatumRodjenja=u.DatumRodenja,
                    Email=u.Email,
                    Telefon=u.Telefon


                }).ToList()
            };
            return View(vm);
        }
        public IActionResult Uspjeh( int UcenikID)
        {


            Ucenik u = db._Ucenik.Where(x => x.KorisnikId == UcenikID ).FirstOrDefault();
            UpisUOdjeljenje uuo = db._UpisUOdjeljenje
                .Include(o=>o.Odjeljenje).Include(n=>n.Odjeljenje.NastavniPlan).Include(g=>g.Odjeljenje.GodinaStudija)
                .Where(y => y.UcenikId == UcenikID
            && y.Odjeljenje.GodinaStudija.TrenutnaGodina).FirstOrDefault();
            UcenikUspjehVM vm = new UcenikUspjehVM()
            {
                UcenikID=u.KorisnikId,
                ImePrezime = u.Ime + " " + u.Prezime,
                UkupnoProsjek=db._OdrzanCasDetalji.Where(x=>x.UpisUOdjeljenjeId==uuo.UpisUOdjeljenjeId).Average(a=>a.Ocjena),
                UkupnoBrojIzostanaka = db._OdrzanCasDetalji.Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(a => a.Odsutan),

                UkupnoBrojOpravdanih = db._OdrzanCasDetalji.Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(a => a.Opravdano),

                UkupnoBrojNeOpravdanih = db._OdrzanCasDetalji.Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(a => a.Odsutan)
                - db._OdrzanCasDetalji.Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(a => a.Opravdano),

                Rows = db._NastavniPlanPredmet.Where(y=>y.NastavniPlanId==uuo.Odjeljenje.NastavniPlanId)
                .Include(p=>p.Predmet)
                .Select(x => new UcenikUspjehVM.Row()
                {
                    Predmet = x.Predmet.Naziv,
                    PredmetID=x.PredmetId== null?0 :(int)x.PredmetId,
                    Prosjek = db._OdrzanCasDetalji
                    .Where(y=>y.OdrzanCas.NastavniPlanPredmetId==x.NastavniPlanPredmetId && y.UpisUOdjeljenjeId==uuo.UpisUOdjeljenjeId).Average(s=>s.Ocjena),
                    BrojIzostanaka = db._OdrzanCasDetalji
                    .Where(y => y.OdrzanCas.NastavniPlanPredmetId == x.NastavniPlanPredmetId && y.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(s => s.Odsutan),
                    BrojOpravdanih= db._OdrzanCasDetalji
                    .Where(y => y.OdrzanCas.NastavniPlanPredmetId == x.NastavniPlanPredmetId && y.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(s => s.Opravdano),

                    BrojNeOpravdanih = db._OdrzanCasDetalji
                    .Where(y => y.OdrzanCas.NastavniPlanPredmetId == x.NastavniPlanPredmetId && y.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(s => s.Odsutan)
                    - db._OdrzanCasDetalji
                    .Where(y => y.OdrzanCas.NastavniPlanPredmetId == x.NastavniPlanPredmetId && y.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId).Count(s => s.Opravdano),
                }).ToList()
            };
            return PartialView(vm);
        }
        public IActionResult UspjehPredmet(int PredmetId, int UcenikID)
        {
            Ucenik u = db._Ucenik.Where(x => x.KorisnikId == UcenikID).FirstOrDefault();
            UpisUOdjeljenje uuo = db._UpisUOdjeljenje
                .Include(o => o.Odjeljenje).Include(n => n.Odjeljenje.NastavniPlan).Include(g => g.Odjeljenje.GodinaStudija)
                .Where(y => y.UcenikId == UcenikID
            && y.Odjeljenje.GodinaStudija.TrenutnaGodina).FirstOrDefault();
            NastavniPlanPredmet npp = db._NastavniPlanPredmet
                .Include(p=>p.Predmet)
                .Where(x => x.PredmetId == PredmetId && x.NastavniPlan.GodinaStudiranjaId == uuo.Odjeljenje.GodinaStudijaId).FirstOrDefault();
            ZakljucnaOcjena zakljucna = db.ZakljucnaOcjena.Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId && x.PredmetID==PredmetId).FirstOrDefault();
            UcenikUspjehPredmetVM vm = new UcenikUspjehPredmetVM()
            {
                UcenikID = u.KorisnikId,
                ImePrezime = u.Ime + " " + u.Prezime,
                Predmet = npp.Predmet.Naziv,
                PredmetID = (int)npp.PredmetId,
                Zakljucena=zakljucna==null? false:true,
                Zakljucna= zakljucna == null ? 0:zakljucna.Ocjena,
                //Odrzani casovi detalji za odredzenog ucenika uuo( koji je upisan u odredzeno odjeljenje i slusa odredzenu godinu studija po odredzenom nastavnom planu)
                //za kojeg su se odrzali casovi iz odredzenog predmeta npp.
                Rows = db._OdrzanCasDetalji
                .Where(x => x.UpisUOdjeljenjeId == uuo.UpisUOdjeljenjeId && x.OdrzanCas.NastavniPlanPredmetId == npp.NastavniPlanPredmetId)
                .Select(z => new UcenikUspjehPredmetVM.Row()
                {
                    DatumOcjenjivanja=z.OdrzanCas.DatumOdrzavanja,
                    Ocjena=(int)z.Ocjena


                }).ToList()
            };
            return PartialView(vm);
        }
        public IActionResult Raspored(int UcenikID) {

            Ucenik u = db._Ucenik.Where(x => x.KorisnikId == UcenikID).FirstOrDefault();
            UpisUOdjeljenje uuo = db._UpisUOdjeljenje
             .Include(o => o.Odjeljenje).Include(n => n.Odjeljenje.NastavniPlan).Include(g => g.Odjeljenje.GodinaStudija)
             .Where(y => y.UcenikId == UcenikID
         && y.Odjeljenje.GodinaStudija.TrenutnaGodina).FirstOrDefault();

            UcenikRasporedVM vm = new UcenikRasporedVM() {
                Odjeljenje=uuo.Odjeljenje.Oznaka,
                Dan=db.Dan.Select(x=> new SelectListItem() { Value=x.DanID.ToString(), Text=x.Naziv}).ToList(),
                PocetankCasa = db.PocetakCasa.Select(x => new SelectListItem() { Value = x.PocetakCasaID.ToString(), Text = x.Pocetak }).ToList(),

                Rows = db.RasporedDetalj.Include(d=>d.Dan).Include(p=>p.PocetakCasa).Include(pr=>pr.Predmet).Where(r=>r.Raspored.OdjeljenjeID==uuo.OdjeljenjeId).Select(x=> new UcenikRasporedVM.Row() {
                    Dan=x.Dan.Naziv,
                    DanId=x.DanID.ToString(),
                    PocetakCasaID=x.PocetakCasaId.ToString(),
                    PocetakCasa=x.PocetakCasa.Pocetak,
                    Predmet=x.Predmet.Naziv

                }).ToList()
                 };
                

            return PartialView(vm); }

    }
}

eSchoolSemi/Areas/AdministratorModul/Views/Ucenik/DodajUcenika.cshtml
@model UcenikDodajVM

@{
    var provjera = ViewData["Provjera"];

    
}
<style>
    .modal-body col-sm-8 {
        margin-bottom: 10px;
    }
</style>

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>




<div id="ucenikDodajM" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Dodaj ucenika</h4>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form method="post" enctype="multipart/form-data" asp-action="SnimiUcenika" id="temp" role="form">
                        <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                        <div class="form-row">
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-offset-2 col-sm-8 ">
                                    <label asp-for="Ime"></label>
                                    <input asp-for="Ime" type="text" class="form-control" />
                                    <span asp-validation-for="Ime" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-8 ">
                                    <label asp-for="Prezime"></label>
                                    <input asp-for="Prezime" type="text" class="form-control" />
                                    <span asp-validation-for="Prezime" class="text-danger"></span>
                                </div>
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-8">
                                    <label asp-for="Username"></label>
                                    <input asp-for="Username" type="text" class="form-control" />
                                    <span asp-validation-for="Username" class="text-danger"></span>
                                </div>
                            </div>


                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="Telefon"></label>
                                <input asp-for="Telefon" type="tel" class="form-control" />
                                <span asp-validation-for="Telefon" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="Email"></label>
                                <input asp-for="Email" type="email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="KorinickaSlika">Upload korisnicke slike</label>
                                <input asp-for="KorinickaSlika" type="file" multiple class="form-control" />
                                <span asp-validation-for="KorinickaSlika" class="text-danger"></span>
                            </div>

                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="DatumRodjenja">Datum rodjenja</label>                   
                                @Html.TextBoxFor(model => model.DatumRodjenja, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", @value=Model.DatumRodjenja })
                                @Html.ValidationMessageFor(m => m.DatumRodjenja, "", new { @class = "text-danger" })

                            </div>
                        </div>



                        <div class="form-group ui-front">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="Roditelj">Unesite prezime i ime roditelja:</label>
                                <input asp-for="Roditelj" type="text" class="form-control" />
                                <span asp-validation-for="Roditelj" class="text-danger"></span>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <label asp-for="GradID">Mjesto stanovanja</label>
                                <select asp-for="GradID" asp-items="@Model.Gradovi" class="form-control"></select>
                            </div>
                        </div>


                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" data-save="modal" data-url="@Url.Action("_tabela", "Ucenik")">Save</button>
            </div>
        </div>

    </div>
</div>

<script>

    $(document).on('click', '#Email', function () {

        var Ime = $("#Ime").val();
        var Prezime = $("#Prezime").val();

        var Email = Ime + "." + Prezime + "@@mail.com";

       

        document.getElementById("Email").value = Email;

    });
    $(document).on('click', '#Username', function () {

        var Ime = $("#Ime").val();
        var Prezime = $("#Prezime").val();

        var Username = Prezime + "." + Ime;



        document.getElementById("Username").value = Username;

    });
    $(document).on('click','#Telefon', function () {

        var Broj1 = Math.floor((Math.random() * 999) + 100);
        var Broj2 = Math.floor((Math.random() * 999) + 100);

        var brojTelefona = "(+387)062-" + Broj1 + "-" + Broj2;
        

        document.getElementById("Telefon").value = brojTelefona;

    });


    $("#Roditelj").autocomplete({
        source: function (request, response) {
            
            $.ajax({
                url: "@Url.Action("nazivRoditelja", "Ucenik")",
                type: "POST",
                dataType: "json",
                data: { Prefix: request.term },
                success: function (data) {
                    response($.map(data, function (item) {
                        return { label: item.text, value: item.text };
                    }))

                }
            })
        }, error: function (xhr, status, error) {
            alert("Error");
        },
        minLength: 2
    });

    $("#Roditelj").autocomplete("option", "appendTo", ".eventInsForm");

</script>
<script src="~/js/ajaxModal.js"></script>

eSchoolSemi/Areas/AdministratorModul/Views/Ucenik/Index.cshtml
@model eSchoolSemi.Web.Helper.PaginatedList<Ucenik>
@{
    ViewData["Title"] = "Index";



    var ucenik = new UcenikDodajVM();

    ucenik.DatumRodjenja = new DateTime(DateTime.Now.Year - 14, DateTime.Now.Month, DateTime.Now.Day);
    ucenik = ViewBag.Gradovi;



}


<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>



<div>

    <div class="container-fluid">
        <div class="row">
            <div class="form-group">
                <div class="col-sm-5 verti">

                    <input type="text" class="form-control" id="ucenikValue" placeholder="Pornadji ucenika" />
                </div>
                <div class="col-sm-3">

                    <button id="dugmeID" class="btn btn-info">Pronadji</button>
                </div>
            </div>
        </div>
    </div>
</div>


<br />
<div class="container-fluid">
    <div class="row">

        <div class="col-sm-2">

            <button type="button" class="btn btn-info" data-toggle="ajax-modal-test23" data-target="#ucenikDodajM" data-url="@Url.Action("DodajUcenika","Ucenik")">Dodaj ucenika</button>
           

        </div>




    </div>
</div>

<br />

<div id="test" data-table="ajaxDiv"></div>
<div id="modalPlaceholder"></div>

<script>

    $(document).ready(function (parametars) {

        $.ajax({
            url: "@Url.Action("_tabela", "Ucenik")", async: false, success: function (result) {
                $("#test").html(result);
            }
        });






    });


    $(function () {

        $('button[data-toggle="ajax-modal-test23"]').click(function (event) {



            event.preventDefault();
            var url = $(this).attr('data-url');
            var placeholder = $('#modalPlaceholder');

            //$.get(url).done(function (data) {

            //    placeholder.html(data);
            //    placeholder.find('.modal').modal('show');
            //});

            $.get({
                url: url, async: false, success: function (result) {
                    
                    placeholder.html(result);
                    placeholder.find('.modal').modal('show');
                }
            });
        });
    });



    $("#ucenikValue").autocomplete({
        source: function (request, response) {
            $.ajax({
                url: "@Url.Action("nazivUcenika", "Ucenik")",
                type: "POST",
                dataType: "json",
                data: { Prefix: request.term },
                success: function (data) {
                    response($.map(data, function (item) {
                        return { label: item.text, value: item.text };
                    }))

                }
            })
        }, error: function (xhr, status, error) {
            alert("Error");
        },
        minLength: 2
    });





    $("#dugmeID").click(function (parametars) {

        var searchString = $("#ucenikValue").val();




        $.ajax({
            url:"/AdministratorModul/Ucenik/_tabela/?searchString=" +searchString,async:false, success: function (result){

                $("#test").html(result);
            }
        });

    });











</script>