eSchoolSemi/Areas/NastavnikModul/Controllers/RazrednikAjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchool.Data.Models;
using eSchoolSemi.Data;
using eSchoolSemi.Data.Models;
using eSchoolSemi.Web.Areas.NastavnikModul.ViewModels;
using eSchoolSemi.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eSchoolSemi.Web.Areas.NastavnikModul.Controllers
{
    [Area("NastavnikModul")]
    [Autorizacija(false, true, false, false)]
    public class RazrednikAjaxController : Controller
    {
        private MojContext _db;
        public RazrednikAjaxController(MojContext db)
        {
            _db = db;
        }
        public IActionResult Index(int OdrzaniCasDetaljiID)
        {
            OdrzanCasDetalji O = _db._OdrzanCasDetalji.Find(OdrzaniCasDetaljiID);

            return PartialView(O);
        }
        public IActionResult Snimi(OdrzanCasDetalji O)
        {
            OdrzanCasDetalji N = _db._OdrzanCasDetalji.Find(O.OdrzanCasDetaljiId);
            N.Ocjena = O.Ocjena;
            N.Opravdano = O.Opravdano;
            N.Odsutan = O.Odsutan;

            _db._OdrzanCasDetalji.Update(N);
            _db.SaveChanges();

            int _OdjeljnjeID = _db._OdrzanCas.Where(x => x.OdrzanCasId == N.OdrzanCasId).First().OdjeljenjeID;


            return RedirectToAction("Edit", "Razrednik", new { OdrzaniCasID = N.OdrzanCasId, OdjeljenjeID = _OdjeljnjeID });
        }
        public IActionResult VladanjeEdit(int UcenikID, int _OdjeljenjeID)
        {
            Ucenik U = _db._Ucenik.Find(UcenikID);

            AjaxVladanjeVM VM = new AjaxVladanjeVM {
                OdjeljenjeID = _OdjeljenjeID,
                UcenikID = U.KorisnikId,
                Vladanje = U.Vladanje,
                Ime = U.Ime + " " + U.Prezime
            };

            return View(VM);
        }
        public IActionResult VladanjeSnimi(AjaxVladanjeVM VM)
        {
            Ucenik U = _db._Ucenik.Find(VM.UcenikID);
            U.Vladanje = VM.Vladanje;

            _db._Ucenik.Update(U);
            _db.SaveChanges();

            return RedirectToAction("Vladanje", "Razrednik", new { OdjeljenjeID = VM.OdjeljenjeID });
        }
    }
}

eSchoolSemi/Areas/NastavnikModul/Views/RazrednikAjax/Index.cshtml
@model eSchool.Data.Models.OdrzanCasDetalji
@*@Html.CheckBoxFor(m=> m.Odsutan)*@

@{
    ViewData["Title"] = "Index";
}

<form asp-action="Snimi" asp-controller="RazrednikAjax" method="post">
    <input asp-for="OdrzanCasDetaljiId" value="@Model.OdrzanCasDetaljiId" hidden />
    @*<div>
            <label>Odsutan</label>
            <input asp-for="Odsutan" type="checkbox" disabled/>
        </div>*@
    <input asp-for="Odsutan" type="checkbox" value="@Model.Odsutan" hidden />

    <div>
        <label>Opravdan</label>
        <input asp-for="Opravdano" type="checkbox" />
    </div>
    <div>
        <label hidden>Ocjena</label>
        <input asp-for="Ocjena" type="number" value="@Model.Ocjena" min="0" max="5" readonly hidden/>
    </div>
    <button class="btn btn-primary" type="submit" value="Snimi">Snimi</button>
</form>


@*<form asp-action="Snimi" asp-controller="Nastavnik" method="post">
        <input asp-for="OdjeljenjeID" value="@Model.OdjeljenjeID" hidden />
        <div>
            <label>Datum</label>
            <input type="datetime" asp-for="DatumOdrzavanja" value="@Model.DatumOdrzavanja" />
        </div>
        <div>
            <label>Predmet</label>
            <select asp-for="PredmetID" asp-items="@Model.Predmeti"></select>
        </div>
        <button class="btn btn-primary" type="submit" value="Snimi">Snimi</button>
    </form>*@

eSchoolSemi/Areas/NastavnikModul/Views/RazrednikAjax/VladanjeEdit.cshtml
@model eSchoolSemi.Web.Areas.NastavnikModul.ViewModels.AjaxVladanjeVM

@{ 
    ViewData["Title"] = "Index";
}

<form asp-action="VladanjeSnimi" asp-controller="RazrednikAjax" method="post">
    <div class="form-group">
        <label>Ime</label>
        <input class="form-control" value="@Model.Ime" readonly />
    </div>

    <div class="form-group">
        <label>Vladanje</label>
        <select class="form-control" asp-for="Vladanje">
            <option value="Primjerno">Primjerno</option>
            <option value="Vrlo Dobro">Vrlo Dobro</option>
            <option value="Dorbo">Dorbo</option>
            <option value="Lose">Lose</option>
            <option value="Katastrofalno">Katastrofalno</option>
        </select>
        <input asp-for="UcenikID" value="@Model.UcenikID" type="number" hidden />
        <input asp-for="OdjeljenjeID" value="@Model.OdjeljenjeID" type="number" hidden />
    </div>

    <button class="btn btn-primary" type="submit" value="Snimi">Snimi</button>
</form>