eSchoolSemi/Controllers/AutentifikacijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchoolSemi.Data;
using eSchoolSemi.Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using eSchoolSemi.Web.ViewModels;
using eSchool.Data.Models;
using eSchoolSemi.Web.Helper;

namespace eSchoolSemi.Web.Controllers
{
    public class AutentifikacijaController : Controller
    {
        private readonly MojContext _context;

        public AutentifikacijaController(MojContext context) => _context = context;
       
        public IActionResult Index()
        {
           
            return View(new LoginVM()
            {
                ZapamtiPassword = true,
            });
        }

        public IActionResult Login(LoginVM input)
        {
            KorisnickiNalog korisnik = _context.korisnickiNalogs
                .SingleOrDefault(x => x.Username == input.username && x.Password == input.password);

            if (korisnik == null)
            {
                TempData["error_poruka"] = "Pogrešan username ili password";
                return View("Index", input);
            }

            Administrator prijavaA = _context.Administrators.FirstOrDefault(x => x.KorisnickiNalogID == korisnik.KorisnickiNalogID);


            Nastavnik prijavaN = _context._Nastavnik.FirstOrDefault(x => x.KorisnickiNalogID == korisnik.KorisnickiNalogID);
            Roditelj prijavaR = _context._Roditelj.FirstOrDefault(x => x.KorisnickiNalogID == korisnik.KorisnickiNalogID);
          

            Ucenik prijavaU = _context._Ucenik.FirstOrDefault(x => x.KorisnickiNalogID == korisnik.KorisnickiNalogID);

            if (prijavaA != null)
            {
                
                korisnik.Zapamti = input.ZapamtiPassword;
                HttpContext.SetLogiraniKorisnik(korisnik,input.ZapamtiPassword);
                return RedirectToAction("Index","Administrator",new { area = "AdministratorModul" });
            }

            if (prijavaN != null)
            {
                korisnik.Zapamti = input.ZapamtiPassword;
                HttpContext.SetLogiraniKorisnik(korisnik, input.ZapamtiPassword);
                //Ovde stavis gdje hoces da ti redirecta Login na koju stranicu
                return RedirectToAction("Index", "Nastavnik", new { area = "NastavnikModul" });
            }
            if (prijavaR != null)
            {
                korisnik.Zapamti = input.ZapamtiPassword;
                HttpContext.SetLogiraniKorisnik(korisnik, input.ZapamtiPassword);
                //Ovde stavis gdje hoces da ti redirecta Login na koju stranicu
                return RedirectToAction("Index", "Roditelj", new { area = "RoditeljModul" });
            } 

            if (prijavaU != null)
            {
                korisnik.Zapamti = input.ZapamtiPassword;
                HttpContext.SetLogiraniKorisnik(korisnik, input.ZapamtiPassword);
                return RedirectToAction("Index", "Ucenik", new { area = "UcenikModul" });
            }
            HttpContext.SetLogiraniKorisnik(korisnik, input.ZapamtiPassword);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult Logout()
        {
            HttpContext.SetLogiraniKorisnik(null);

            return RedirectToAction("Index");
        }
        
       
    }
}

eSchoolSemi/Areas/RoditeljModul/Views/Shared/_Layout.cshtml
@using eSchoolSemi.Data.Models
@using eSchoolSemi.Web.Helper

@{

    KorisnickiNalog username = Context.GetLogiraniKorisnik();

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eSchoolSemi</title>

    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="/css/site.css" />
    <link rel="stylesheet" href="~/css/SideBarCss.css" />



    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.0.0.min.js"></script>








    <script src="/lib/bootstrap/dist/js/bootstrap.js"></script>





</head>
<body>
    <div class="wrapper" id="nesto">
        <!--Top navbar-->
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-left">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">E-School</a>
                <button type="button" id="sidebarCollapse" class="btn btn-default navbar-btn" style="background-color:lightgrey">
                    <i class="glyphicon glyphicon-th-list"></i>

                </button>
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Autentifikacija" asp-action="Logout">@(username?.Username) <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                </ul>
            </div>

        </nav>
        <!-- Sidebar Holder -->
        <nav id="sidebar">
            <div class="sidebar-header text-center">
                <img src="~/images/School icon.png" height="72" width="72" class="img-circle" />
            </div>

            <ul class="list-unstyled components">

                <li> <a asp-area="RoditeljModul" asp-controller="Roditelj" asp-action="Index">Pocetna</a></li>
                <li> <a asp-area="RoditeljModul" asp-controller="Sastanak" asp-action="Index">Roditeljski Sastanci</a></li>
                <li> <a asp-area="RoditeljModul" asp-controller="Ucenik" asp-action="Index">Podatci o djetetu</a></li>
                <li> <a asp-area="RoditeljModul" asp-controller="Obavijest" asp-action="Index">Obavijesti</a></li>
                <li> <a asp-area="RoditeljModul" asp-controller="NastavniPlanProgram" asp-action="Index">Nastavni plan i program</a></li>

                @*<li>
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false">Menu Razrednika</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li><a asp-area="NastavnikModul" asp-controller="Razrednik" asp-action="Index">Odjeljenja</a></li>
                <li><a asp-area="NastavnikModul" asp-controller="Razrednik" asp-action="Vladanje">Vladanje</a></li>
                <li><a asp-area="NastavnikModul" asp-controller="Nastavnik" asp-action="Index">Nastavnici</a></li>
            </ul>
        </li>*@
                @*<li>
            <a asp-area="NastavnikModul" asp-controller="Obavijest" asp-action="Index">Obavjesti</a>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">Nastava</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li><a asp-area="NastavnikModul" asp-controller="OdrzaniCas" asp-action="Index">Casovi</a></li>
                <li><a asp-area="RoditeljModul" asp-controller="Materijali" asp-action="Index">Materijali</a></li>
            </ul>
        </li>*@

            </ul>


        </nav>

        <!-- Page Content Holder -->
        <div id="content">
            <div class="container-fluid">


                @RenderBody()
                <hr />



            </div>

        </div>
    </div>


    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>




</body>
</html>