eSchoolSemi/Areas/AdministratorModul/Controllers/RasporedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchoolSemi.Data;
using eSchoolSemi.Data.Models;
using eSchoolSemi.Web.Areas.AdministratorModul.ViewModels;
using eSchoolSemi.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace eSchoolSemi.Web.Areas.AdministratorModul.Controllers
{
    [Area("AdministratorModul")]
    [Autorizacija(false, false, false, true)]
    public class RasporedController : Controller
    {

        private MojContext _context;
        public RasporedController(MojContext context) => _context = context;

        public IActionResult Index()
        {
            IEnumerable<Raspored> listaRasporeda = _context.Raspored.ToList();
            return View(listaRasporeda);
        }

        public IActionResult DodajRaspored(int OdjeljenjeId)
        {
            var Odjeljenje = _context._Odjeljenje.First(x => x.OdjeljenjeId == OdjeljenjeId);

            RasporedDodajVM noviRaspored = new RasporedDodajVM {

                OdljenjeID=Odjeljenje.OdjeljenjeId,
                Oznaka=Odjeljenje.Oznaka

            };

            
           

            return PartialView(noviRaspored);
        }


        public IActionResult SnimiRaspored(RasporedDodajVM obj) {

            Raspored rasporedZaSnimit = new Raspored
            {

                Naziv = obj.RasporedNaziv,
                OdjeljenjeID = obj.OdljenjeID
            };

            _context.Raspored.Add(rasporedZaSnimit);
            _context.SaveChanges();

            return RedirectToAction("Detalji", "Odjeljenje",new { id =obj.OdljenjeID});
        }


        public IActionResult UrediRaspored(int id) {

            Raspored raspored = _context.Raspored.FirstOrDefault(x => x.RasporedID == id);

            RasporedDetaljVM viewModel = new RasporedDetaljVM
            {
                RasporedID = raspored.RasporedID,
                OdjeljenjeId=raspored.OdjeljenjeID,

                Predmet = _context._Predmet.Select(x => new SelectListItem {

                    Text = x.Naziv,
                    Value = x.PredmetId.ToString()
                }).ToList(),

                Dan = _context.Dan.Select(x => new SelectListItem
                {

                    Text = x.Naziv,
                    Value = x.DanID.ToString()
                }).ToList(),

                PocetakCasa = _context.PocetakCasa.Select(x => new SelectListItem
                {

                    Text = x.Pocetak,
                    Value = x.PocetakCasaID.ToString()
                }).ToList()
            };

            return View(viewModel);
        }

        public IActionResult DodajDetalj(RasporedDetaljVM vM)
        {
            if (vM.PredmetId == 0) {
                
                RasporedDetalj zaIzabrisat = _context.RasporedDetalj.
                                            FirstOrDefault(x => x.RasporedID == vM.RasporedID &&
                                                           x.DanID == vM.DanId &&
                                                           x.PocetakCasaId == vM.PocetakCasaId);

                _context.RasporedDetalj.Remove(zaIzabrisat);
                return RedirectToAction("UrediRaspored", new { id = vM.RasporedID });
            }


            RasporedDetalj promjena = _context.RasporedDetalj.
                                            FirstOrDefault(x => x.RasporedID == vM.RasporedID &&
                                                           x.DanID == vM.DanId && 
                                                           x.PocetakCasaId == vM.PocetakCasaId);


            if (promjena != null)
            {
                promjena.PredmetID = vM.PredmetId;
                _context.RasporedDetalj.Update(promjena);
            }

            else
            {
                RasporedDetalj detalji = new RasporedDetalj
                {
                    RasporedID = vM.RasporedID,
                    PredmetID = vM.PredmetId,
                    DanID = vM.DanId,
                    PocetakCasaId = vM.PocetakCasaId
                };

                _context.RasporedDetalj.Add(detalji);
            }

            _context.SaveChanges();

            return RedirectToAction("UrediRaspored",new {id=vM.RasporedID});
        }


        public IActionResult CitavRaspored(int RasporedID) {

            PregledRasporedVM listaPredmeta = new PregledRasporedVM {

                listaPredmeta=_context.RasporedDetalj.Where(x=>x.RasporedID==RasporedID).
                Select(x=>new PregledRasporedVM.Row {
                    Predmet=x.Predmet.Naziv,
                    Dan=x.Dan.Naziv,
                    PocetakCasa=x.PocetakCasa.Pocetak
                }).ToList()
            };

            return PartialView(listaPredmeta);
        }

        public IActionResult CitavRasporedUredi(int RasporedID)
        {

            PregledRasporedVM listaPredmeta = new PregledRasporedVM
            {

                listaPredmeta = _context.RasporedDetalj.Where(x => x.RasporedID == RasporedID).
                Select(x => new PregledRasporedVM.Row
                {
                    Predmet = x.Predmet.Naziv,
                    Dan = x.Dan.Naziv,
                    PocetakCasa = x.PocetakCasa.Pocetak
                }).ToList()
            };

            return PartialView(listaPredmeta);
        }
    }
}

eSchoolSemi/Areas/UcenikModul/Controllers/RasporedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eSchool.Data.Models;
using eSchoolSemi.Data;
using eSchoolSemi.Data.Models;
using eSchoolSemi.Web.Areas.UcenikModul.ViewModels;
using eSchoolSemi.Web.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace eSchoolSemi.Web.Areas.UcenikModul.Controllers
{
    [Area("UcenikModul")]
    [Autorizacija(true, false, false, false)]
    public class RasporedController : Controller
    {
        private MojContext db;
        public RasporedController(MojContext _db) { db = _db; }
        public IActionResult Index()
        {
            KorisnickiNalog k = HttpContext.GetLogiraniKorisnik();
            Korisnik ucenik = db._Korisnik.Where(x => x.KorisnickiNalogID == k.KorisnickiNalogID).FirstOrDefault();

        
            UpisUOdjeljenje uuo = db._UpisUOdjeljenje
             .Include(o => o.Odjeljenje).Include(n => n.Odjeljenje.NastavniPlan).Include(g => g.Odjeljenje.GodinaStudija)
             .Where(y => y.UcenikId == ucenik.KorisnikId
         && y.Odjeljenje.GodinaStudija.TrenutnaGodina).FirstOrDefault();

            RasporedIndexVM vm = new RasporedIndexVM()
            {
                Odjeljenje = uuo.Odjeljenje.Oznaka,
                Dan = db.Dan.Select(x => new SelectListItem() { Value = x.DanID.ToString(), Text = x.Naziv }).ToList(),
                PocetankCasa = db.PocetakCasa.Select(x => new SelectListItem() { Value = x.PocetakCasaID.ToString(), Text = x.Pocetak }).ToList(),

                Rows = db.RasporedDetalj.Include(d => d.Dan).Include(p => p.PocetakCasa).Include(pr => pr.Predmet).Where(r => r.Raspored.OdjeljenjeID == uuo.OdjeljenjeId).Select(x => new RasporedIndexVM.Row()
                {
                    Dan = x.Dan.Naziv,
                    DanId = x.DanID.ToString(),
                    PocetakCasaID = x.PocetakCasaId.ToString(),
                    PocetakCasa = x.PocetakCasa.Pocetak,
                    Predmet = x.Predmet.Naziv

                }).ToList()
            };
            return View(vm);
        }
     
    }
}

eSchoolSemi/Areas/AdministratorModul/Views/Raspored/CitavRaspored.cshtml
@model PregledRasporedVM
@{
    ViewData["Title"] = "CitavRaspored";
}




<div class="modal fade" id="rasporedPregled" tabindex="-1" role="dialog" aria-labelledby="addContactLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="addContactLabel">Raspored</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <table id="rasporedTabela" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Ponedeljak</th>
                            <th>Utorak</th>
                            <th>Srijeda</th>
                            <th>Cetvrtak</th>
                            <th>Petak</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < 7; i++)
                        {
                            <tr>
                                @for (int j = 0; j < 5; j++)
                                {
                                    <td>N/A</td>
                                }
                            </tr>
                        }
                    </tbody>

                </table>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function CreateTable(Predmet, Dan, Cas) {

        var i = 1;
        var j = 1;

        switch (Dan) {

            case "Ponedeljak":
                j = 0;
                break;
            case "Utorak":
                j = 1;
                break;
            case "Srijeda":
                j = 2;
                break;
            case "Cetvrtak":
                j = 3;
                break;
            default:
                j = 4;
        }

        switch (Cas) {

            case "7:00":
                i = 1;
                break;
            case "7:50":
                i = 2;
                break;
            case "8:35":
                i = 3;
                break;
            case "9:35":
                i = 4;
                break;
            case "10:25":
                i = 5;
                break;
            case "11:15":
                i = 6;
                break;
            default:
                i = 7;
        }


        document.getElementById("rasporedTabela").rows[i].cells[j].innerHTML = "(" + Cas + ")" + " " + Predmet;
    };


</script>

@foreach (var item in Model.listaPredmeta)
{

    <script>CreateTable("@item.Predmet","@item.Dan","@item.PocetakCasa")</script>

};

eSchoolSemi/Areas/AdministratorModul/Views/Raspored/CitavRasporedUredi.cshtml
@model PregledRasporedVM
@{
    ViewData["Title"] = "CitavRaspored";
}

<h2>CitavRaspored</h2>



<table id="rasporedTabela" class="table table-bordered">
    <thead>
        <tr>
            <th>Ponedeljak</th>
            <th>Utorak</th>
            <th>Srijeda</th>
            <th>Cetvrtak</th>
            <th>Petak</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < 7; i++)
        {
            <tr>
                @for (int j = 0; j < 5; j++)
                {
                    <td>N/A</td>
                }
            </tr>
        }
    </tbody>

</table>



<script>
    function CreateTable(Predmet, Dan, Cas) {

        var i = 1;
        var j = 1;

        switch (Dan) {

            case "Ponedeljak":
                j = 0;
                break;
            case "Utorak":
                j = 1;
                break;
            case "Srijeda":
                j = 2;
                break;
            case "Cetvrtak":
                j = 3;
                break;
            default:
                j = 4;
        }

        switch (Cas) {

            case "7:00":
                i = 1;
                break;
            case "7:50":
                i = 2;
                break;
            case "8:35":
                i = 3;
                break;
            case "9:35":
                i = 4;
                break;
            case "10:25":
                i = 5;
                break;
            case "11:15":
                i = 6;
                break;
            default:
                i = 7;
        }


        document.getElementById("rasporedTabela").rows[i].cells[j].innerHTML ="("+Cas+")"+" "+ Predmet;
     };


</script>

@foreach (var item in Model.listaPredmeta)
{

    <script>CreateTable("@item.Predmet","@item.Dan","@item.PocetakCasa")</script>

};

eSchoolSemi/Areas/AdministratorModul/Views/Raspored/DodajRaspored.cshtml
@model RasporedDodajVM
@{
    ViewData["Title"] = "DodajRaspored";
}

<div class="modal fade" id="dodajRaspored" tabindex="-1" role="dialog" aria-labelledby="dodajNastavnikLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-center" id="dodajNastavnikLabel">Dodaj raspored!</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <form asp-action="SnimiRaspored" method="post">

                        <input asp-for="OdljenjeID" type="hidden" value="@Model.OdljenjeID" class="form-control" />

                        <div class="row">
                            <div class="form-group col-md-8 col-md-push-2">
                                <label asp-for="OdljenjeID">Odjeljenje</label>
                                <input asp-for="Oznaka" type="text" value="@Model.Oznaka" class="form-control" disabled />
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-md-8 col-md-push-2">
                                <label asp-for="RasporedNaziv">Naziv rasporeda:</label>
                                <input asp-for="RasporedNaziv" type="text" class="form-control" />
                            </div>
                        </div>
                        <div class="text-center">
                            <button class="btn btn-info" type="submit">Snimi</button>
                        </div>
                       
                    </form>

                </div>
            </div>

           
        </div>
    </div>
</div>

eSchoolSemi/Areas/AdministratorModul/Views/Raspored/Index.cshtml
@using eSchoolSemi.Data.Models
@model IEnumerable<Raspored>
    @{
        ViewData["Title"] = "Index";
    }

    <h2>Index</h2>

<div class="container">
    <div class="row">
        <div class="col">
            <table class="table table-responsive">
                <thead>
                    <tr>
                        <td>Naziv</td>
                        <td>Akcija</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        @foreach (var raspored in Model)
                        {
                            <td>@raspored.Naziv</td>
                            <td><a asp-action="UrediRaspored" asp-route-id="@raspored.RasporedID" class="btn btn-info">Uredi</a></td>
                        }
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

eSchoolSemi/Areas/AdministratorModul/Views/Raspored/UrediRaspored.cshtml
@model RasporedDetaljVM
@{
    ViewData["Title"] = "UrediRaspored";
}


<a asp-action="Detalji" asp-controller="Odjeljenje" asp-route-id="@Model.OdjeljenjeId" class="btn btn-danger">Nazad u odjeljenje</a>
<div class="container-fluid">
    <form asp-action="DodajDetalj" method="post">
        <div class="row">
            <input asp-for="RasporedID" value="@Model.RasporedID" hidden/>
            <div class="form-group col-sm-4">
                <label asp-for="PredmetId">Predmet</label>
                <select asp-for="PredmetId" asp-items="@Model.Predmet" class="form-control">
                    
                </select>
            </div>

            <div class="form-group col-sm-4">
                <label asp-for="Dan"></label>
                <select asp-for="DanId" asp-items="@Model.Dan" class="form-control"></select>
            </div>

            <div class="form-group col-sm-4">
                <label asp-for="PocetakCasaId"> Pocetak casa</label>
                <select asp-for="PocetakCasaId" asp-items="@Model.PocetakCasa" class="form-control"></select>
            </div>
        </div>

        <button type="submit" class="btn btn-success">Dodaj</button>
    </form>
</div>

<div id="raspored"></div>

<script>
    $(document).ready(function (parametars) {

        $.get("@Url.Action("CitavRasporedUredi", "Raspored", new { RasporedID = Model.RasporedID })", function (rezultat, status) {

            $("#raspored").html(rezultat);
        });

    });

</script>